### ISSUE TITLE
Exported dump doesn't include dependencies

### ISSUE THREAD

**Issue by twoolworth** [dankeder/pg_dump_sample#2]
So one of the main reasons why I'm attempting to utilize your tool is for the claim of it including dependent tables / rows. What I'm finding though is that it is only including the table I reference within my manifest file.

Here is the command I'm running:
`pg_dump_sample /m filter.yaml /h localhost /U postgres /f mydb_dump.sql TestSample`

Here is my manifest file:
`tables:`
`  - table: dbo."Teams"`

I've also attached a simplified version of my database that replicates the issue I'm talking about. Exporting the Teams table should end up extracting information for every other table listed in the database because of the FK's throughout.

[Sample Database Schema](https://github.com/dankeder/pg_dump_sample/files/735744/dump-TestSample-201701270933.txt)

Here's the output I'm currently receiving upon running the command referenced above. You'll see it only includes the 1 row for Teams.
[mydb_dump.txt](https://github.com/dankeder/pg_dump_sample/files/735749/mydb_dump.txt)

**Comment by dankeder** [comment]
Thanks for the DB schema and manifest, I found the bug (or rather a missing feature). The script wasn't dumping tables which were missing in the manifest (even if other tables depend on them).

I think I added/fixed that, please give it a try.

If you are interested in the gory details, see here: 507ada0
