### ISSUE TITLE
PGPASSWORD environment variable is not accommodated

### ISSUE THREAD

**Issue by glenwild** [dankeder/pg_dump_sample#4]
Dan,

Typically with **pg_dump** I can perform
`PGPASSWORD=some_secret pg_dump -U some_user some_dbname`
and I will not be prompted for a password.

However, performing a similar attempt with **pg_dump_sample**, using
`PGPASSWORD=some_secret pg_dump_sample -U some_user some_dbname -w my.yaml`
I get prompted with
`Password for some_user: `

Hopefully this is something that can be addressed.

Thanks in advance,
Rick (glenwild)

**Comment by dankeder** [comment]
Hi Rick, thanks for the suggestion. I don't have much time lately so I don't know when I'll get to it. Pull requests are welcome though.

**Comment by dankeder** [comment]
Hi, I modified the tool to support environment variables. Note that they have lower precedence than command-line options.

On the sidenote, I also integrated the repo with TravisCI so the repo is built automatically and binaries are available for download in Releases section.
